#Udacity - NanoDegree - Project 4 - Identifying POI

##Project Goal
The goal of this project is to develop and tune a supervised classification algorithm to identify persons of interest (POI) in the Enron scandal based on a combination of publically available Enron financial data and email records. The modest goals are to have recall and precision scores above 0.3.  

The compiled data set contains information for 144 people employed at Enron, a ‘Travel Agency in the Park’, and the total compensations for all of these sources. Additionally, the Udacity.com course designer created email features that give the total number of e-mails sent and received for each user, and the total number of emails sent to and receieved from a POI. Of the 144 people, 18 of them are labeled as POIs.

Lets start by reading in the data;

In [1]:
import sys
import pickle
import numpy as np
import pandas as pd

#Load Udacity Tools for Testing Results
sys.path.append("../tools/")
from feature_format import featureFormat, targetFeatureSplit
from tester import test_classifier, dump_classifier_and_data

### Load the dictionary containing the dataset
data_dict = pickle.load(open("final_project_dataset.pkl", "r") )
data = pd.DataFrame.from_dict(data_dict)
#Remove Invalide Rows
data = data.drop(['TOTAL','THE TRAVEL AGENCY IN THE PARK'],axis=1)
data = data.transpose()
#Give Each Person their own row
data

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
ALLEN PHILLIP K,4175000,2869717,-3081055,NaN,phillip.allen@enron.com,1729541,13868,2195,47,65,...,304805,152,False,126027,-126027,201955,1407,2902,4484442,1729541
BADUM JAMES P,NaN,178980,NaN,NaN,NaN,257817,3486,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,182466,257817
BANNANTINE JAMES M,NaN,NaN,-5104,NaN,james.bannantine@enron.com,4046157,56301,29,39,0,...,NaN,864523,False,1757552,-560222,477,465,566,916197,5243487
BAXTER JOHN C,1200000,1295738,-1386055,NaN,NaN,6680544,11200,NaN,NaN,NaN,...,1586055,2660303,False,3942714,NaN,267102,NaN,NaN,5634343,10623258
BAY FRANKLIN R,400000,260455,-201641,NaN,frank.bay@enron.com,NaN,129142,NaN,NaN,NaN,...,NaN,69,False,145796,-82782,239671,NaN,NaN,827696,63014
BAZELIDES PHILIP J,NaN,684694,NaN,NaN,NaN,1599641,NaN,NaN,NaN,NaN,...,93750,874,False,NaN,NaN,80818,NaN,NaN,860136,1599641
BECK SALLY W,700000,NaN,NaN,NaN,sally.beck@enron.com,NaN,37172,4343,144,386,...,NaN,566,False,126027,NaN,231330,2639,7315,969068,126027
BELDEN TIMOTHY N,5249999,2144013,-2334434,NaN,tim.belden@enron.com,953136,17355,484,228,108,...,NaN,210698,True,157569,NaN,213999,5521,7991,5501630,1110705
BELFER ROBERT,NaN,-102500,NaN,3285,NaN,3285,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,44093,NaN,NaN,NaN,102500,-44093
BERBERIAN DAVID,NaN,NaN,NaN,NaN,david.berberian@enron.com,1624396,11892,NaN,NaN,NaN,...,NaN,NaN,False,869220,NaN,216582,NaN,NaN,228474,2493616
BERGSIEKER RICHARD P,250000,NaN,-485813,NaN,rick.bergsieker@enron.com,NaN,59175,59,4,0,...,180250,427316,False,659249,NaN,187922,233,383,618850,659249
BHATNAGAR SANJAY,NaN,NaN,NaN,137864,sanjay.bhatnagar@enron.com,2604490,NaN,29,0,1,...,NaN,137864,False,-2604490,15456290,NaN,463,523,15456290,NaN
BIBI PHILIPPE A,1000000,NaN,NaN,NaN,philippe.bibi@enron.com,1465734,38559,40,23,8,...,369721,425688,False,378082,NaN,213625,1336,1607,2047593,1843816
BLACHMAN JEREMY M,850000,NaN,NaN,NaN,jeremy.blachman@enron.com,765313,84208,14,25,2,...,831809,272,False,189041,NaN,248546,2326,2475,2014835,954354
BLAKE JR. NORMAN P,NaN,NaN,-113784,113784,NaN,NaN,1279,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,1279,NaN
BOWEN JR RAYMOND M,1350000,NaN,-833,NaN,raymond.bowen@enron.com,NaN,65907,27,140,15,...,974293,1621,True,252055,NaN,278601,1593,1858,2669589,252055
BROWN MICHAEL,NaN,NaN,NaN,NaN,michael.brown@enron.com,NaN,49288,41,13,1,...,NaN,NaN,False,NaN,NaN,NaN,761,1486,49288,NaN
BUCHANAN HAROLD G,500000,NaN,NaN,NaN,john.buchanan@enron.com,825464,600,125,0,0,...,304805,1215,False,189041,NaN,248017,23,1088,1054637,1014505
BUTTS ROBERT H,750000,NaN,-75000,NaN,bob.butts@enron.com,NaN,9410,NaN,NaN,NaN,...,175000,150656,False,417619,NaN,261516,NaN,NaN,1271582,417619
BUY RICHARD B,900000,649584,-694862,NaN,rick.buy@enron.com,2542813,NaN,1053,156,71,...,769862,400572,False,901657,NaN,330546,2333,3523,2355702,3444470
CALGER CHRISTOPHER F,1250000,NaN,-262500,NaN,christopher.calger@enron.com,NaN,35818,144,199,25,...,375304,486,True,126027,NaN,240189,2188,2598,1639297,126027
CARTER REBECCA C,300000,NaN,-159792,NaN,rebecca.carter@enron.com,NaN,NaN,15,29,7,...,75000,540,False,307301,-307301,261809,196,312,477557,NaN
CAUSEY RICHARD A,1000000,NaN,-235000,NaN,richard.causey@enron.com,NaN,30674,49,58,12,...,350000,307895,True,2502063,NaN,415189,1585,1892,1868758,2502063
CHAN RONNIE,NaN,NaN,-98784,98784,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,32460,-32460,NaN,NaN,NaN,NaN,NaN
CHRISTODOULOU DIOMEDES,NaN,NaN,NaN,NaN,diomedes.christodoulou@enron.com,5127155,NaN,NaN,NaN,NaN,...,NaN,NaN,False,950730,NaN,NaN,NaN,NaN,NaN,6077885
CLINE KENNETH W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,662086,-472568,NaN,NaN,NaN,NaN,189518
COLWELL WESLEY,1200000,27610,-144062,NaN,wes.colwell@enron.com,NaN,16514,40,240,11,...,NaN,101740,True,698242,NaN,288542,1132,1758,1490344,698242
CORDES WILLIAM R,NaN,NaN,NaN,NaN,bill.cordes@enron.com,651850,NaN,12,10,0,...,NaN,NaN,False,386335,NaN,NaN,58,764,NaN,1038185
COX DAVID,800000,NaN,-41250,NaN,chip.cox@enron.com,117551,27861,33,0,4,...,NaN,494,False,378082,NaN,314288,71,102,1101393,495633
CUMBERLAND MICHAEL S,325000,NaN,NaN,NaN,NaN,NaN,22344,NaN,NaN,NaN,...,275000,713,False,207940,NaN,184899,NaN,NaN,807956,207940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAVAGE FRANK,NaN,NaN,-121284,125034,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,3750,NaN
SCRIMSHAW MATTHEW,NaN,NaN,NaN,NaN,matthew.scrimshaw@enron.com,759557,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,759557
SHANKMAN JEFFREY A,2000000,NaN,NaN,NaN,jeffrey.shankman@enron.com,1441898,178979,2681,94,83,...,554422,1191,False,630137,NaN,304110,1730,3221,3038702,2072035
SHAPIRO RICHARD S,650000,NaN,NaN,NaN,richard.shapiro@enron.com,607837,137767,1215,74,65,...,NaN,705,False,379164,NaN,269076,4527,15149,1057548,987001
SHARP VICTORIA T,600000,187469,NaN,NaN,vicki.sharp@enron.com,281073,116337,136,24,6,...,422158,2401,False,213063,NaN,248146,2477,3136,1576511,494136
SHELBY REX,200000,NaN,-4167,NaN,rex.shelby@enron.com,1624396,22884,39,13,14,...,NaN,1573324,True,869220,NaN,211844,91,225,2003885,2493616
SHERRICK JEFFREY B,NaN,NaN,NaN,NaN,jeffrey.sherrick@enron.com,1426469,NaN,25,39,18,...,NaN,NaN,False,405999,NaN,NaN,583,613,NaN,1832468
SHERRIFF JOHN R,1500000,NaN,NaN,NaN,john.sherriff@enron.com,1835558,NaN,92,28,23,...,554422,1852186,False,1293424,NaN,428780,2103,3187,4335388,3128982
SKILLING JEFFREY K,5600000,NaN,NaN,NaN,jeff.skilling@enron.com,19250000,29336,108,88,30,...,1920000,22122,True,6843672,NaN,1111258,2042,3627,8682716,26093672
STABLER FRANK,500000,NaN,NaN,NaN,frank.stabler@enron.com,NaN,16514,NaN,NaN,NaN,...,NaN,356071,False,511734,NaN,239502,NaN,NaN,1112087,511734
SULLIVAN-SHAKLOVITZ COLLEEN,100000,181993,NaN,NaN,NaN,1362375,NaN,NaN,NaN,NaN,...,554422,162,False,NaN,NaN,162779,NaN,NaN,999356,1362375
SUNDE MARTIN,700000,NaN,NaN,NaN,marty.sunde@enron.com,NaN,NaN,38,37,13,...,476451,111122,False,698920,NaN,257486,2565,2647,1545059,698920
TAYLOR MITCHELL S,600000,227449,NaN,NaN,mitchell.taylor@enron.com,3181250,NaN,29,0,0,...,NaN,NaN,False,563798,NaN,265214,300,533,1092663,3745048
THORN TERENCE H,NaN,16586,NaN,NaN,terence.thorn@enron.com,4452476,46145,41,0,0,...,200000,426629,False,365320,NaN,222093,73,266,911453,4817796
TILNEY ELIZABETH A,300000,NaN,-575000,NaN,elizabeth.tilney@enron.com,591250,NaN,19,10,11,...,275000,152055,False,576792,NaN,247338,379,460,399393,1168042
UMANOFF ADAM S,788750,NaN,NaN,NaN,adam.umanoff@enron.com,NaN,53122,18,12,0,...,NaN,NaN,False,NaN,NaN,288589,41,111,1130461,NaN
URQUHART JOHN A,NaN,NaN,-36666,36666,NaN,NaN,228656,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,228656,NaN
WAKEHAM JOHN,NaN,NaN,NaN,109298,NaN,NaN,103773,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,213071,NaN
WALLS JR ROBERT H,850000,NaN,NaN,NaN,rob.walls@enron.com,4346544,50936,146,17,0,...,540751,2,False,1552453,NaN,357091,215,671,1798780,5898997
WALTERS GARETH W,NaN,53625,NaN,NaN,NaN,1030329,33785,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,87410,1030329
WASAFF GEORGE,325000,831299,-583325,NaN,george.wasaff@enron.com,1668260,NaN,30,22,7,...,200000,1425,False,388167,NaN,259996,337,400,1034395,2056427
WESTFAHL RICHARD K,NaN,NaN,-10800,NaN,dick.westfahl@enron.com,NaN,51870,NaN,NaN,NaN,...,256191,401130,False,384930,NaN,63744,NaN,NaN,762135,384930
WHALEY DAVID A,NaN,NaN,NaN,NaN,NaN,98718,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,98718
WHALLEY LAWRENCE G,3000000,NaN,NaN,NaN,greg.whalley@enron.com,3282960,57838,556,186,24,...,808346,301026,False,2796177,NaN,510364,3920,6019,4677574,6079137
WHITE JR THOMAS E,450000,NaN,NaN,NaN,thomas.white@enron.com,1297049,81353,NaN,NaN,NaN,...,NaN,1085463,False,13847074,NaN,317543,NaN,NaN,1934359,15144123
WINOKUR JR. HERBERT S,NaN,NaN,-25000,108579,NaN,NaN,1413,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,84992,NaN
WODRASKA JOHN,NaN,NaN,NaN,NaN,john.wodraska@enron.com,NaN,NaN,NaN,NaN,NaN,...,NaN,189583,False,NaN,NaN,NaN,NaN,NaN,189583,NaN
WROBEL BRUCE,NaN,NaN,NaN,NaN,NaN,139130,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,139130
YEAGER F SCOTT,NaN,NaN,NaN,NaN,scott.yeager@enron.com,8308552,53947,NaN,NaN,NaN,...,NaN,147950,True,3576206,NaN,158403,NaN,NaN,360300,11884758
YEAP SOON,NaN,NaN,NaN,NaN,NaN,192758,55097,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,55097,192758

In regards to the financial information, I defined outliers as having values that are more than 3 standard deviations from the mean value for the group. This is not the traditional definition or criteria for an outlier which is 1.5 times the interquartile range below the first quartile or Above the third quartile. I used my definition after I have replaced missing values with zero. Using this definition of outliers there are 25 people in the data set that are financial outliers:

In [3]:
finance = ['salary',
             'deferral_payments',
             'total_payments',
             'exercised_stock_options',
             'bonus',
             'restricted_stock',
             'restricted_stock_deferred',
             'total_stock_value',
             'expenses',
             'loan_advances',
             'other',
             'director_fees',
             'deferred_income',
             'long_term_incentive']

from scipy import stats
#Use unique because some people are financial outliers in multiple variables
data[np.abs(stats.zscore(data[finance].replace('NaN',0.0))) > 3].index.unique()

array(['ALLEN PHILLIP K', 'BELDEN TIMOTHY N', 'BHATNAGAR SANJAY',
       'BLAKE JR. NORMAN P', 'FREVERT MARK A', 'GRAMM WENDY L',
       'HANNON KEVIN P', 'HIRKO JOSEPH', 'HORTON STANLEY C',
       'HUMPHREY GENE E', 'JAEDICKE ROBERT', 'LAVORATO JOHN J',
       'LAY KENNETH L', 'LEMAISTRE CHARLES', 'MARTIN AMANDA K',
       'MCCLELLAN GEORGE', 'MENDELSOHN JOHN', 'PAI LOU L',
       'RICE KENNETH D', 'SAVAGE FRANK', 'SHANKMAN JEFFREY A',
       'SKILLING JEFFREY K', 'URQUHART JOHN A', 'WAKEHAM JOHN',
       'WHITE JR THOMAS E', 'WINOKUR JR. HERBERT S'], dtype=object)

This accounts for 17% of the data being considered an outlier and also contains 33% of the POI. Ultimately I decided that financial outliers were relevant information, and decided not to remove them from the data for this analysis.

##New Feature

I decided to create two features I thought were be informative to the data: the ratio of emails received from a POI to the total number of emails received and the ratio of emails sent to a POI to the total number of emails sent.
I thought these features would be more informative than the total number of emails sent or received from a POI because it normalizes by how active or how popular a person is.

If a person sends 10 emails, and 5 of them are to a POI, that seems more relevant than if a person sends 1000 emails and 5 of them are to a POI. A person who sends 50% of their emails to a person of interest seems more suspect than a person who only sends 0.5% of their emails to a POI.

The inverse is not true, however. If a person received 10 emails from a POI, that is as relevant regardless if the person receives 20 emails or 2000 emails. The important idea is that how often is a POI is contacting this person, and how does that affect the likelihood that a person is also a POI. This ratio does not capture that idea, but I created it because I was willing to be proven wrong.

In [4]:
data.from_this_person_to_poi = data.from_this_person_to_poi.astype(float)
data.from_poi_to_this_person = data.from_poi_to_this_person.astype(float)
data.to_messages = data.to_messages.astype(float)
data.from_messages = data.from_messages.astype(float)
data['from_this_person_to_poi_ratio'] = data.from_this_person_to_poi/data.to_messages
data['from_poi_to_this_person_ratio'] = data.from_poi_to_this_person/data.from_messages
data = data.replace('NaN',0.0)

After the creation of these features I used sklearn's Pipeline, FeatureUnion, and GridSearch to search through a combintation of variable to find the set of features that gave the best performance for a Decision Tree Classifier.  I search between 1 and 9 of the best features using a 5 folds stratified cross validation to gauge performance for each set.  I am using a f1 score to maximize the weight combintation of recall and precision.

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import StratifiedKFold
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.grid_search import GridSearchCV
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_curve
from sklearn.learning_curve import learning_curve

tru = data.poi.values
trn = data.drop(['poi','email_address'],axis=1).values
clf = DecisionTreeClassifier()

#pca = PCA(n_components=2)
selection = SelectKBest(k=1)
#combined_features = FeatureUnion([("pca", pca), ("univ_select", selection)])
combined_features = FeatureUnion([("univ_select", selection)])

X_features = combined_features.fit(trn, tru).transform(trn)

pipeline = Pipeline([("features", combined_features), ("clf", clf)])

#param_grid = dict(features__pca__n_components=range(0,15),
#                  features__univ_select__k=range(1,10))

param_grid = dict(features__univ_select__k=range(1,10))

skf = StratifiedKFold(tru, n_folds=5)
grid_search = GridSearchCV(pipeline, cv=skf, param_grid=param_grid, scoring='f1')
grid_search.fit(trn, tru)
print grid_search.best_score_
print grid_search.best_params_
var_scores = grid_search.best_estimator_.steps[0][1].get_params()['univ_select'].scores_
print var_scores
num_features = grid_search.best_params_['features__univ_select__k']
best_features = data.drop(['poi','email_address'],axis=1).columns[np.argsort(var_scores)[::-1][:num_features]]
best_features

0.36813973064
{'features__univ_select__k': 3}
[ 21.06000171   0.21705893  11.59554766   2.10765594  25.09754153
   6.23420114   0.1641645    5.34494152   2.42650813   7.2427304
  10.07245453   4.24615354   9.34670079   0.06498431  18.57570327
   8.74648553   1.69882435   8.87383526  24.46765405   4.16908382
   5.20965022]

Index([u'exercised_stock_options', u'total_stock_value', u'bonus'], dtype='object')

##Result of Search

The search is finished and the best f1 score of 0.368 with 3 'best features'.  Because of the random shuffling involved in the scoring, it is possible to get a variety in number and combintations of best features.  

The best features for predicting if a person is a person of interest are financal features: Exercised stock options, total stock value, and bonus.  Even when the number of best features fluxuate, these 3 are always among them.   

##Turning Model
Using the paramemters from the above search we will now tune the classifier to optimize its performance. I am searching through the spliting and depth criteria for the Decision Tree Classifier.

In [17]:
tru = data.poi.values
trn = data[best_features].values
clf = DecisionTreeClassifier()
pipeline = Pipeline([("clf", clf)])

param_grid = dict(clf__criterion=("gini","entropy"),
                  clf__min_samples_split=[1,2,4,8,16,32],
                   clf__min_samples_leaf=[1,2,4,8,16,32],
                   clf__max_depth=[None,1,2,4,8,16,32])

skf = StratifiedKFold(tru, n_folds=5)
grid_search = GridSearchCV(pipeline, cv=skf, param_grid=param_grid, scoring='f1')
grid_search.fit(trn, tru)
print grid_search.best_params_
print grid_search.best_score_
best_clf = grid_search.best_estimator_
best_clf

{'clf__criterion': 'gini', 'clf__max_depth': 32, 'clf__min_samples_leaf': 1, 'clf__min_samples_split': 1}
0.47075617284

Pipeline(steps=[('clf', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=32,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=1, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best'))])

The best parameters for the Decision Tree Classifier has a max depth of 32, a min sample leaf size of 1, and requires at least 1 values to split the tree when fitting.  These results produced the best averge f1 score of 0.47.   

##Importance of Validation

Validation is an attempt to confirm that a model will give reasonable or consistent results on new, untrained data. A classic mistake is to test the results of a model on the data used to train the model. This is no doubt give the best possible score, but can over fit the data leading to less than desired results on new data. Validation protects against this mistake by training the model on one set of data and testing on yet another.

I used 5-Fold Statfied Cross Validation for investigating and comparing algorithms in this analysis. This is where there the algorithm is trained on the on the data 5 times using 80% of the data as a training set and 20% of the data as a testing set.  Each set has approxiamately the same ratio of positive and negative examples of POI.  Each time this is done, the training and testing set are shuffled to create a new 80/20 split on the data. I then used the average performance as an estimate of its performance on new data.

## Final Performance

Using the Udacity 'test_classifier' function I evaluate my classifer to see if the recall and precision scores are both greater than 0.3.

In [18]:
#tt = pd.DataFrame(pca.fit_transform(trn),index=data.index)
#data2 = data.join(tt)
#print data2.columns
my_data = data.transpose().to_dict()
features =  best_features.tolist()
features = ['poi']+features
test_classifier(best_clf, my_data, features)

Pipeline(steps=[('clf', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=32,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=1, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best'))])
	Accuracy: 0.80492	Precision: 0.37066	Recall: 0.38400	F1: 0.37721	F2: 0.38125
	Total predictions: 13000	True positives:  768	False positives: 1304	False negatives: 1232	True negatives: 9696

The results of the tuned classifier are shown above.   The average precision of the 13000 prediction is 37% and the average recall is 38%.   The precision value is that out of all predictions of people being a POI, 38% of them are actually POI.  The recall value is that out of all of the POI, 37% are actually predicted to be POI by my tuned classifier.